# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: ECS API
  description: ECS mobiel app API
  version: "1.0.0"
# the domain of the service
host: localhost:8080
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /
resourcePath: /Badges
description: All about Badges API
apis:

- path: /badges
  operations:

  - httpMethod: POST
    summary: Creates a badge
    notes: Returns a badge based
    responseClass: Badge
    nickname: createBadge
    consumes:
      - multipart/form-data
    produces:
      - application/json

    parameters:

    - name: name
      dataType: string
      paramType: formData
      required: true
      description: Badge name

    - name: position
      dataType: string
      paramType: formData
      required: true
      description: Badge position

    - name: expiresOn
      dataType: date
      paramType: formData
      required: true
      description: Badge expiry date

    - name: image
      dataType: file
      paramType: formData
      required: true
      description: Badge photo


  - httpMethod: GET
    summary: Retrives all the badges
    notes: Returns all the badge based on badge name
    responseClass: Badge
    nickname: Get badges
    consumes:
      - application/json

models:
    Badge:
      id: Badge
      properties:
        name:
          type: String
          required: true
        position:
          type: String
          required: true
        expiresOn:
            type: Date
            required: true
        photo:
            type: Image
            required: true
